[package]
name = "auralis-simd"
description = "SIMD backends for Auralis."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
simd = ["dep:rten-simd"]

[dependencies]
rten-simd = { version = "0.24.0", optional = true }

[lints]
workspace = true
