[package]
name = "auralis-wav"
description = "WAV codec implementation for Auralis."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
simd = ["auralis-simd/simd"]

[dependencies]
auralis-codec = { path = "../auralis-codec" }
auralis-core = { path = "../auralis-core" }
auralis-simd = { path = "../auralis-simd", default-features = false }
hound.workspace = true
symphonia.workspace = true
thiserror.workspace = true

[lints]
workspace = true
