[package]
name = "auralis"
description = "High-level library API for Auralis."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[features]
default = []
simd = ["auralis-effects/simd", "auralis-simd/simd", "auralis-wav/simd"]

[dependencies]
auralis-aiff = { path = "../auralis-aiff" }
auralis-au = { path = "../auralis-au" }
auralis-codec = { path = "../auralis-codec", features = ["auralis-flac", "auralis-wav"] }
auralis-core = { path = "../auralis-core" }
auralis-effects = { path = "../auralis-effects" }
auralis-flac = { path = "../auralis-flac" }
auralis-raw = { path = "../auralis-raw" }
auralis-simd = { path = "../auralis-simd", default-features = false }
auralis-wav = { path = "../auralis-wav" }
thiserror.workspace = true

[lints]
workspace = true
