[package]
name = "auralis"
description = "High-level library API for Auralis."
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
auralis-core = { path = "../auralis-core" }
auralis-effects = { path = "../auralis-effects" }
auralis-wav = { path = "../auralis-wav" }
thiserror.workspace = true

[lints]
workspace = true
