//! SoX-ng effect names tracked by the Auralis coverage plan.

/// Known SoX-ng effect names, including effects that are not implemented yet.
pub const KNOWN_SOX_NG_EFFECTS: &[&str] = &[
    "allpass",
    "band",
    "bandpass",
    "bandreject",
    "bass",
    "bend",
    "biquad",
    "centercut",
    "channels",
    "chorus",
    "compand",
    "contrast",
    "dcshift",
    "deemph",
    "delay",
    "dither",
    "dolbyb",
    "dop",
    "downsample",
    "earwax",
    "echo",
    "echos",
    "equalizer",
    "fade",
    "fir",
    "firfit",
    "flanger",
    "gain",
    "highpass",
    "hilbert",
    "ladspa",
    "loudness",
    "lowpass",
    "mcompand",
    "noiseprof",
    "noisered",
    "norm",
    "oops",
    "overdrive",
    "pad",
    "phaser",
    "pitch",
    "rate",
    "remix",
    "repeat",
    "reverb",
    "reverse",
    "riaa",
    "saturation",
    "sdm",
    "silence",
    "sinc",
    "softvol",
    "speed",
    "splice",
    "stat",
    "stats",
    "stretch",
    "swap",
    "synth",
    "tempo",
    "treble",
    "tremolo",
    "trim",
    "upsample",
    "vad",
    "vol",
];

/// Returns a stable classification diagnostic for known SoX-ng effects that
/// Auralis must not treat as ordinary missing coverage.
pub(crate) fn classified_sox_ng_effect_diagnostic(name: &str) -> Option<&'static str> {
    match name {
        "dolbyb" => Some(
            "blocked in Auralis: SoX-ng uses GPLv2 libdolbyb C code while Auralis is MIT and pure Rust; use `sox_ng ... dolbyb ...` for Dolby B processing or provide a compatible pure-Rust/public-domain spec",
        ),
        "dop" => Some(
            "not planned in the Auralis effect registry: DoP is DSD-over-PCM transport packing from 1-bit DSD into 24-bit PCM samples, while Auralis currently processes PCM16 WAV audio effects; use `sox_ng ... dop ...` for DoP transport or wait for future DSD/DoP format support",
        ),
        "ladspa" => Some(
            "blocked in Auralis: LADSPA support requires loading native external plugins through LADSPA_PATH and a plugin-host ABI, while Auralis currently accepts only MIT-compatible pure Rust effects; use `sox_ng ... ladspa ...` for LADSPA plugins or wait for a future external-host boundary",
        ),
        "sdm" => Some(
            "not planned in the Auralis effect registry: SDM is a DSD-oriented sigma-delta modulator that emits 1-bit output using SoX-ng's LGPL filter tables and trellis behavior, while Auralis currently processes PCM16 WAV audio effects; use `sox_ng ... sdm ...` for SDM processing or wait for future DSD/1-bit format support",
        ),
        _ => None,
    }
}
